'use client';

import React from 'react';
import { Images, Ratio } from 'lucide-react';
import type { UmbraUiPipelineResolutionCapability } from '../../../../shared/umbra-ui/pipelineTypes';
import {
  UMBRA_IMAGE_ASPECT_PRESETS,
  resolveUmbraImageDimensions,
  type UmbraImageAspectPresetId,
} from '@/lib/umbraUiImageResolution';

interface UmbraImageResolutionControlsProps {
  aspectRatio: UmbraImageAspectPresetId;
  baseResolution: number;
  width: string;
  height: string;
  batchSize: number;
  resolution: UmbraUiPipelineResolutionCapability;
  onAspectRatioChange: (value: UmbraImageAspectPresetId) => void;
  onBaseResolutionChange: (value: number) => void;
  onDimensionsChange: (width: string, height: string, manual?: boolean) => void;
  onBatchSizeChange: (value: number) => void;
}

const inputClass = 'w-full rounded-md border border-white/10 bg-black/35 px-2.5 py-2 text-xs text-zinc-100 outline-none transition-colors focus:border-cyan-300/45';
const labelClass = 'text-[9px] font-black uppercase tracking-[0.14em] text-zinc-500';

export function UmbraImageResolutionControls({
  aspectRatio,
  baseResolution,
  width,
  height,
  batchSize,
  resolution,
  onAspectRatioChange,
  onBaseResolutionChange,
  onDimensionsChange,
  onBatchSizeChange,
}: UmbraImageResolutionControlsProps) {
  const resolutionAdjustable = resolution.support === 'adjustable';
  const applyPreset = React.useCallback((nextAspect: UmbraImageAspectPresetId, nextBase: number) => {
    if (!resolutionAdjustable) return;
    const dimensions = resolveUmbraImageDimensions(nextAspect, nextBase, resolution);
    if (dimensions) onDimensionsChange(String(dimensions.width), String(dimensions.height));
  }, [onDimensionsChange, resolution, resolutionAdjustable]);

  const handleAspectChange = (nextAspect: UmbraImageAspectPresetId) => {
    onAspectRatioChange(nextAspect);
    applyPreset(nextAspect, baseResolution);
  };

  const handleBaseChange = (nextBase: number) => {
    const normalized = Math.max(512, Math.min(2048, Math.round(nextBase / 64) * 64));
    onBaseResolutionChange(normalized);
    applyPreset(aspectRatio, normalized);
  };

  return (
    <section className="overflow-hidden rounded-md border border-white/10 bg-white/[0.02]">
      <header className="flex min-h-9 items-center gap-2 border-b border-white/[0.08] px-2.5">
        <Ratio size={13} className="text-cyan-300" />
        <span className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-200">
          {resolutionAdjustable ? 'Aspect & Resolution' : 'Output'}
        </span>
        <span className="ml-auto font-mono text-[10px] text-cyan-100">{width}x{height}</span>
      </header>

      <div className="space-y-2.5 p-2.5">
        <div className={resolutionAdjustable ? 'grid grid-cols-[minmax(0,1fr)_84px] gap-2' : ''}>
          {resolutionAdjustable ? (
            <label className="min-w-0 space-y-1.5">
              <span className={labelClass}>Aspect Ratio</span>
              <select
                value={aspectRatio}
                onChange={(event) => handleAspectChange(event.target.value as UmbraImageAspectPresetId)}
                className={inputClass}
              >
                {UMBRA_IMAGE_ASPECT_PRESETS.map((preset) => (
                  <option key={preset.id} value={preset.id}>{preset.label}</option>
                ))}
                <option value="custom">Custom</option>
              </select>
            </label>
          ) : null}
          <label className="space-y-1.5">
            <span className={labelClass}>Batch Count</span>
            <input
              type="number"
              min={1}
              max={64}
              step={1}
              value={batchSize}
              onChange={(event) => onBatchSizeChange(Math.max(1, Math.min(64, Number(event.target.value) || 1)))}
              className={inputClass}
              title="Images generated by each queued prompt"
            />
          </label>
        </div>

        {resolutionAdjustable ? (
          <label className="block space-y-1.5">
            <span className="flex items-center gap-2">
              <span className={labelClass}>Base Resolution</span>
              <span className="ml-auto font-mono text-[10px] text-zinc-300">{baseResolution}px</span>
            </span>
            <input
              type="range"
              min={512}
              max={2048}
              step={64}
              value={baseResolution}
              disabled={aspectRatio === 'custom'}
              onChange={(event) => handleBaseChange(Number(event.target.value))}
              className="h-5 w-full accent-cyan-300 disabled:cursor-not-allowed disabled:opacity-30"
            />
          </label>
        ) : null}

        {resolutionAdjustable ? (
          <div className="grid grid-cols-2 gap-2">
            <label className="space-y-1.5">
              <span className={labelClass}>Width</span>
              <input
                value={width}
                inputMode="numeric"
                onChange={(event) => onDimensionsChange(event.target.value, height, true)}
                className={inputClass}
              />
            </label>
            <label className="space-y-1.5">
              <span className={labelClass}>Height</span>
              <input
                value={height}
                inputMode="numeric"
                onChange={(event) => onDimensionsChange(width, event.target.value, true)}
                className={inputClass}
              />
            </label>
          </div>
        ) : null}

        <div className="flex items-center gap-1.5 border-t border-white/[0.07] pt-2 font-mono text-[9px] text-zinc-600">
          <Images size={10} />
          <span>{batchSize} image{batchSize === 1 ? '' : 's'} per queue item</span>
        </div>
      </div>
    </section>
  );
}
