// Finite owned HTTP ingress identities. Generated from the certified inventory; no caller data is rendered.
export type ActionGroup = 'Gallery' | 'Umbra UI' | 'Data Forge' | 'Model Manager' | 'Shared';
export type ActionProcess = 'Gallery' | 'Umbra main';
export type ActionIdentity = { route: string; group: ActionGroup };
export const actionRoutes = [
  {"method": "GET","route": "/api/fs/folder-summary","group": "Gallery","process": "Gallery","display": "/api/fs/folder-summary","suffix": false},
  {"method": "GET","route": "/api/fs/image","group": "Gallery","process": "Gallery","display": "/api/fs/image","suffix": false},
  {"method": "GET","route": "/api/fs/list-progressive","group": "Gallery","process": "Gallery","display": "/api/fs/list-progressive","suffix": false},
  {"method": "GET","route": "/api/fs/metadata","group": "Gallery","process": "Gallery","display": "/api/fs/metadata","suffix": false},
  {"method": "GET","route": "/api/fs/metadata-search","group": "Gallery","process": "Gallery","display": "/api/fs/metadata-search","suffix": false},
  {"method": "GET","route": "/api/fs/search","group": "Gallery","process": "Gallery","display": "/api/fs/search","suffix": false},
  {"method": "GET","route": "/api/fs/thumbnail","group": "Gallery","process": "Gallery","display": "/api/fs/thumbnail","suffix": false},
  {"method": "GET","route": "/api/fs/tree","group": "Gallery","process": "Gallery","display": "/api/fs/tree","suffix": false},
  {"method": "GET","route": "/api/fs/tree-changes","group": "Gallery","process": "Gallery","display": "/api/fs/tree-changes","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/folder-summary","group": "Gallery","process": "Gallery","display": "/api/fs/folder-summary","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/image","group": "Gallery","process": "Gallery","display": "/api/fs/image","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/list-progressive","group": "Gallery","process": "Gallery","display": "/api/fs/list-progressive","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/metadata","group": "Gallery","process": "Gallery","display": "/api/fs/metadata","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/metadata-search","group": "Gallery","process": "Gallery","display": "/api/fs/metadata-search","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/search","group": "Gallery","process": "Gallery","display": "/api/fs/search","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/thumbnail","group": "Gallery","process": "Gallery","display": "/api/fs/thumbnail","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/tree","group": "Gallery","process": "Gallery","display": "/api/fs/tree","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/tree-changes","group": "Gallery","process": "Gallery","display": "/api/fs/tree-changes","suffix": false},
  {"method": "POST","route": "/api/fs/empty-folders/delete","group": "Gallery","process": "Gallery","display": "/api/fs/empty-folders/delete","suffix": false},
  {"method": "POST","route": "/api/fs/empty-folders/preview","group": "Gallery","process": "Gallery","display": "/api/fs/empty-folders/preview","suffix": false},
  {"method": "POST","route": "/api/fs/mkdir","group": "Gallery","process": "Gallery","display": "/api/fs/mkdir","suffix": false},
  {"method": "POST","route": "/api/fs/reorder","group": "Gallery","process": "Gallery","display": "/api/fs/reorder","suffix": false},
  {"method": "POST","route": "/api/fs/tags/add","group": "Gallery","process": "Gallery","display": "/api/fs/tags/add","suffix": false},
  {"method": "POST","route": "/api/fs/tags/set","group": "Gallery","process": "Gallery","display": "/api/fs/tags/set","suffix": false},
  {"method": "ANY","route": "/api/debug/log","group": "Shared","process": "Umbra main","display": "/api/debug/log","suffix": false},
  {"method": "ANY","route": "/api/files/datasets/:relativePath","group": "Data Forge","process": "Umbra main","display": "/api/files/datasets/:relativePath","suffix": false},
  {"method": "ANY","route": "/api/umbra-ui/agent","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/agent","suffix": false},
  {"method": "ANY","route": "/api/umbra-ui/agent/:rest","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/agent/:rest","suffix": false},
  {"method": "ANY","route": "/api/umbra-ui/mcp","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/mcp","suffix": false},
  {"method": "DELETE","route": "/api/dataset/api-keys","group": "Data Forge","process": "Umbra main","display": "/api/dataset/api-keys","suffix": false},
  {"method": "DELETE","route": "/api/datasets/:id","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id","suffix": false},
  {"method": "DELETE","route": "/api/datasets/:id/concept/:id","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/concept/:id","suffix": false},
  {"method": "DELETE","route": "/api/editor/presets/:id","group": "Shared","process": "Umbra main","display": "/api/editor/presets/:id","suffix": false},
  {"method": "DELETE","route": "/api/editor/tags/:id","group": "Shared","process": "Umbra main","display": "/api/editor/tags/:id","suffix": false},
  {"method": "DELETE","route": "/api/model-manager/civitai/auth","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/auth","suffix": false},
  {"method": "DELETE","route": "/api/model-manager/downloads","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/downloads","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/favorites","group": "Shared","process": "Umbra main","display": "/api/powerprompter/favorites","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/queue-history","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-history","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/queue-state","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-state","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/queues","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queues","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/session","group": "Shared","process": "Umbra main","display": "/api/powerprompter/session","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/wildcards","group": "Shared","process": "Umbra main","display": "/api/powerprompter/wildcards","suffix": false},
  {"method": "DELETE","route": "/api/powerprompter/wildcards/:name","group": "Shared","process": "Umbra main","display": "/api/powerprompter/wildcards/:name","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/canvas-studio/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects/:projectId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/canvas/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/canvas/projects/:projectId/restore-points/:revisionId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/restore-points/:revisionId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/inpaint/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/inpaint/projects/:projectId/snapshots/:revisionId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId/snapshots/:revisionId","suffix": false},
  {"method": "DELETE","route": "/api/umbra-ui/video-jobs","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-jobs","suffix": false},
  {"method": "DELETE","route": "/api/user-config","group": "Shared","process": "Umbra main","display": "/api/user-config","suffix": false},
  {"method": "GET","route": "/api/app/releases","group": "Shared","process": "Umbra main","display": "/api/app/releases","suffix": false},
  {"method": "GET","route": "/api/app/update/state","group": "Shared","process": "Umbra main","display": "/api/app/update/state","suffix": false},
  {"method": "GET","route": "/api/app/update/status","group": "Shared","process": "Umbra main","display": "/api/app/update/status","suffix": false},
  {"method": "GET","route": "/api/booru/autocomplete","group": "Data Forge","process": "Umbra main","display": "/api/booru/autocomplete","suffix": false},
  {"method": "GET","route": "/api/booru/corpus/related","group": "Data Forge","process": "Umbra main","display": "/api/booru/corpus/related","suffix": false},
  {"method": "GET","route": "/api/booru/corpus/status","group": "Data Forge","process": "Umbra main","display": "/api/booru/corpus/status","suffix": false},
  {"method": "GET","route": "/api/booru/dataset-generator/status","group": "Data Forge","process": "Umbra main","display": "/api/booru/dataset-generator/status","suffix": false},
  {"method": "GET","route": "/api/booru/image-proxy","group": "Data Forge","process": "Umbra main","display": "/api/booru/image-proxy","suffix": false},
  {"method": "GET","route": "/api/booru/search","group": "Data Forge","process": "Umbra main","display": "/api/booru/search","suffix": false},
  {"method": "GET","route": "/api/cache/stats","group": "Shared","process": "Umbra main","display": "/api/cache/stats","suffix": false},
  {"method": "GET","route": "/api/comfy/staged-video-metadata","group": "Shared","process": "Umbra main","display": "/api/comfy/staged-video-metadata","suffix": false},
  {"method": "GET","route": "/api/comfy/staged-video-preview","group": "Shared","process": "Umbra main","display": "/api/comfy/staged-video-preview","suffix": false},
  {"method": "GET","route": "/api/data-forge/ai-toolkit/status","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/ai-toolkit/status","suffix": false},
  {"method": "GET","route": "/api/data-forge/model-merge/blueprints","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/blueprints","suffix": true},
  {"method": "GET","route": "/api/data-forge/model-merge/loras","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/loras","suffix": true},
  {"method": "GET","route": "/api/data-forge/model-merge/models","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/models","suffix": true},
  {"method": "GET","route": "/api/data-forge/model-merge/recipes","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/recipes","suffix": true},
  {"method": "GET","route": "/api/data-forge/model-merge/status","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/status","suffix": true},
  {"method": "GET","route": "/api/data-forge/wildcard-generator/classifiers","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/wildcard-generator/classifiers","suffix": false},
  {"method": "GET","route": "/api/data-forge/wildcard-generator/tags","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/wildcard-generator/tags","suffix": false},
  {"method": "GET","route": "/api/dataset/api-keys","group": "Data Forge","process": "Umbra main","display": "/api/dataset/api-keys","suffix": false},
  {"method": "GET","route": "/api/dataset/caption-models","group": "Data Forge","process": "Umbra main","display": "/api/dataset/caption-models","suffix": false},
  {"method": "GET","route": "/api/dataset/images","group": "Data Forge","process": "Umbra main","display": "/api/dataset/images","suffix": false},
  {"method": "GET","route": "/api/dataset/list","group": "Data Forge","process": "Umbra main","display": "/api/dataset/list","suffix": false},
  {"method": "GET","route": "/api/datasets","group": "Data Forge","process": "Umbra main","display": "/api/datasets","suffix": false},
  {"method": "GET","route": "/api/datasets/:id/concept/:id/images","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/concept/:id/images","suffix": false},
  {"method": "GET","route": "/api/datasets/:id/concept/:id/settings","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/concept/:id/settings","suffix": false},
  {"method": "GET","route": "/api/editor/config/:key","group": "Shared","process": "Umbra main","display": "/api/editor/config/:key","suffix": false},
  {"method": "GET","route": "/api/editor/meta","group": "Shared","process": "Umbra main","display": "/api/editor/meta","suffix": false},
  {"method": "GET","route": "/api/editor/order/get","group": "Shared","process": "Umbra main","display": "/api/editor/order/get","suffix": false},
  {"method": "GET","route": "/api/editor/presets","group": "Shared","process": "Umbra main","display": "/api/editor/presets","suffix": false},
  {"method": "GET","route": "/api/editor/search","group": "Shared","process": "Umbra main","display": "/api/editor/search","suffix": false},
  {"method": "GET","route": "/api/editor/tags","group": "Shared","process": "Umbra main","display": "/api/editor/tags","suffix": false},
  {"method": "GET","route": "/api/files","group": "Shared","process": "Umbra main","display": "/api/files","suffix": false},
  {"method": "GET","route": "/api/fs/archives","group": "Gallery","process": "Umbra main","display": "/api/fs/archives","suffix": false},
  {"method": "GET","route": "/api/fs/archives/download","group": "Gallery","process": "Umbra main","display": "/api/fs/archives/download","suffix": false},
  {"method": "GET","route": "/api/fs/archives/status","group": "Gallery","process": "Umbra main","display": "/api/fs/archives/status","suffix": false},
  {"method": "GET","route": "/api/fs/copy/status","group": "Gallery","process": "Umbra main","display": "/api/fs/copy/status","suffix": false},
  {"method": "GET","route": "/api/fs/download-archive","group": "Gallery","process": "Umbra main","display": "/api/fs/download-archive","suffix": false},
  {"method": "GET","route": "/api/fs/folder-summary","group": "Gallery","process": "Umbra main","display": "/api/fs/folder-summary","suffix": false},
  {"method": "GET","route": "/api/fs/generated-media-activity","group": "Gallery","process": "Umbra main","display": "/api/fs/generated-media-activity","suffix": false},
  {"method": "GET","route": "/api/fs/image","group": "Gallery","process": "Umbra main","display": "/api/fs/image","suffix": false},
  {"method": "GET","route": "/api/fs/list","group": "Gallery","process": "Umbra main","display": "/api/fs/list","suffix": false},
  {"method": "GET","route": "/api/fs/list-progressive","group": "Gallery","process": "Umbra main","display": "/api/fs/list-progressive","suffix": false},
  {"method": "GET","route": "/api/fs/metadata","group": "Gallery","process": "Umbra main","display": "/api/fs/metadata","suffix": false},
  {"method": "GET","route": "/api/fs/metadata-search","group": "Gallery","process": "Umbra main","display": "/api/fs/metadata-search","suffix": false},
  {"method": "GET","route": "/api/fs/move/status","group": "Gallery","process": "Umbra main","display": "/api/fs/move/status","suffix": false},
  {"method": "GET","route": "/api/fs/preview","group": "Gallery","process": "Umbra main","display": "/api/fs/preview","suffix": false},
  {"method": "GET","route": "/api/fs/read","group": "Gallery","process": "Umbra main","display": "/api/fs/read","suffix": false},
  {"method": "GET","route": "/api/fs/search","group": "Gallery","process": "Umbra main","display": "/api/fs/search","suffix": false},
  {"method": "GET","route": "/api/fs/search-suggestions","group": "Gallery","process": "Umbra main","display": "/api/fs/search-suggestions","suffix": false},
  {"method": "GET","route": "/api/fs/tags/summary","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/summary","suffix": false},
  {"method": "GET","route": "/api/fs/thumbnail","group": "Gallery","process": "Umbra main","display": "/api/fs/thumbnail","suffix": false},
  {"method": "GET","route": "/api/fs/tree","group": "Gallery","process": "Umbra main","display": "/api/fs/tree","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/folder-summary","group": "Gallery","process": "Umbra main","display": "/api/fs/folder-summary","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/image","group": "Gallery","process": "Umbra main","display": "/api/fs/image","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/list-progressive","group": "Gallery","process": "Umbra main","display": "/api/fs/list-progressive","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/metadata","group": "Gallery","process": "Umbra main","display": "/api/fs/metadata","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/metadata-search","group": "Gallery","process": "Umbra main","display": "/api/fs/metadata-search","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/search","group": "Gallery","process": "Umbra main","display": "/api/fs/search","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/search-suggestions","group": "Gallery","process": "Umbra main","display": "/api/fs/search-suggestions","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/tags/summary","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/summary","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/thumbnail","group": "Gallery","process": "Umbra main","display": "/api/fs/thumbnail","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/tree","group": "Gallery","process": "Umbra main","display": "/api/fs/tree","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/fs/tree-changes","group": "Gallery","process": "Umbra main","display": "/api/fs/tree-changes","suffix": false},
  {"method": "GET","route": "/api/gallery-bridge/status","group": "Gallery","process": "Umbra main","display": "/api/gallery-bridge/status","suffix": false},
  {"method": "GET","route": "/api/healthz","group": "Shared","process": "Umbra main","display": "/api/healthz","suffix": false},
  {"method": "GET","route": "/api/healthz/live","group": "Shared","process": "Umbra main","display": "/api/healthz/live","suffix": false},
  {"method": "GET","route": "/api/healthz/ready","group": "Shared","process": "Umbra main","display": "/api/healthz/ready","suffix": false},
  {"method": "GET","route": "/api/images","group": "Shared","process": "Umbra main","display": "/api/images","suffix": false},
  {"method": "GET","route": "/api/local-server-proxy/health","group": "Shared","process": "Umbra main","display": "/api/local-server-proxy/health","suffix": false},
  {"method": "GET","route": "/api/model-manager/civitai/auth","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/auth","suffix": false},
  {"method": "GET","route": "/api/model-manager/civitai/model","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/model","suffix": false},
  {"method": "GET","route": "/api/model-manager/civitai/preview-metadata","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/preview-metadata","suffix": false},
  {"method": "GET","route": "/api/model-manager/civitai/search","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/search","suffix": false},
  {"method": "GET","route": "/api/model-manager/civitai/version","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/version","suffix": false},
  {"method": "GET","route": "/api/model-manager/downloads","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/downloads","suffix": false},
  {"method": "GET","route": "/api/model-manager/downloads/:id","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/downloads/:id","suffix": false},
  {"method": "GET","route": "/api/model-manager/fs/copy/status","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/copy/status","suffix": false},
  {"method": "GET","route": "/api/model-manager/fs/move/status","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/move/status","suffix": false},
  {"method": "GET","route": "/api/model-manager/list","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/list","suffix": false},
  {"method": "GET","route": "/api/model-manager/media","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/media","suffix": false},
  {"method": "GET","route": "/api/model-manager/opened-models","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/opened-models","suffix": false},
  {"method": "GET","route": "/api/model-manager/roots","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/roots","suffix": false},
  {"method": "GET","route": "/api/model-manager/tree","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/tree","suffix": false},
  {"method": "GET","route": "/api/onboarding/status","group": "Shared","process": "Umbra main","display": "/api/onboarding/status","suffix": false},
  {"method": "GET","route": "/api/powerprompter/api-workflows","group": "Shared","process": "Umbra main","display": "/api/powerprompter/api-workflows","suffix": false},
  {"method": "GET","route": "/api/powerprompter/api-workflows/open","group": "Shared","process": "Umbra main","display": "/api/powerprompter/api-workflows/open","suffix": false},
  {"method": "GET","route": "/api/powerprompter/backend-queue-debug","group": "Shared","process": "Umbra main","display": "/api/powerprompter/backend-queue-debug","suffix": false},
  {"method": "GET","route": "/api/powerprompter/cards","group": "Shared","process": "Umbra main","display": "/api/powerprompter/cards","suffix": false},
  {"method": "GET","route": "/api/powerprompter/classifiers","group": "Shared","process": "Umbra main","display": "/api/powerprompter/classifiers","suffix": false},
  {"method": "GET","route": "/api/powerprompter/csv/list","group": "Shared","process": "Umbra main","display": "/api/powerprompter/csv/list","suffix": false},
  {"method": "GET","route": "/api/powerprompter/favorites","group": "Shared","process": "Umbra main","display": "/api/powerprompter/favorites","suffix": false},
  {"method": "GET","route": "/api/powerprompter/queue-history","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-history","suffix": false},
  {"method": "GET","route": "/api/powerprompter/queue-state","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-state","suffix": false},
  {"method": "GET","route": "/api/powerprompter/queues","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queues","suffix": false},
  {"method": "GET","route": "/api/powerprompter/receipt","group": "Shared","process": "Umbra main","display": "/api/powerprompter/receipt","suffix": false},
  {"method": "GET","route": "/api/powerprompter/search","group": "Shared","process": "Umbra main","display": "/api/powerprompter/search","suffix": false},
  {"method": "GET","route": "/api/powerprompter/selections","group": "Shared","process": "Umbra main","display": "/api/powerprompter/selections","suffix": false},
  {"method": "GET","route": "/api/powerprompter/session","group": "Shared","process": "Umbra main","display": "/api/powerprompter/session","suffix": false},
  {"method": "GET","route": "/api/powerprompter/settings","group": "Shared","process": "Umbra main","display": "/api/powerprompter/settings","suffix": false},
  {"method": "GET","route": "/api/powerprompter/wildcards","group": "Shared","process": "Umbra main","display": "/api/powerprompter/wildcards","suffix": false},
  {"method": "GET","route": "/api/remote/auth/pair","group": "Shared","process": "Umbra main","display": "/api/remote/auth/pair","suffix": false},
  {"method": "GET","route": "/api/remote/auth/status","group": "Shared","process": "Umbra main","display": "/api/remote/auth/status","suffix": false},
  {"method": "GET","route": "/api/remote/devices","group": "Shared","process": "Umbra main","display": "/api/remote/devices","suffix": false},
  {"method": "GET","route": "/api/remote/metrics","group": "Shared","process": "Umbra main","display": "/api/remote/metrics","suffix": false},
  {"method": "GET","route": "/api/remote/metrics/ping","group": "Shared","process": "Umbra main","display": "/api/remote/metrics/ping","suffix": false},
  {"method": "GET","route": "/api/remote/status","group": "Shared","process": "Umbra main","display": "/api/remote/status","suffix": false},
  {"method": "GET","route": "/api/search","group": "Shared","process": "Umbra main","display": "/api/search","suffix": false},
  {"method": "GET","route": "/api/settings","group": "Shared","process": "Umbra main","display": "/api/settings","suffix": false},
  {"method": "GET","route": "/api/settings/bundle","group": "Shared","process": "Umbra main","display": "/api/settings/bundle","suffix": false},
  {"method": "GET","route": "/api/system/stats","group": "Shared","process": "Umbra main","display": "/api/system/stats","suffix": false},
  {"method": "GET","route": "/api/tools/actions/:id","group": "Shared","process": "Umbra main","display": "/api/tools/actions/:id","suffix": false},
  {"method": "GET","route": "/api/tools/comfyui/versions","group": "Shared","process": "Umbra main","display": "/api/tools/comfyui/versions","suffix": false},
  {"method": "GET","route": "/api/tools/detect","group": "Shared","process": "Umbra main","display": "/api/tools/detect","suffix": false},
  {"method": "GET","route": "/api/tools/updates","group": "Shared","process": "Umbra main","display": "/api/tools/updates","suffix": false},
  {"method": "GET","route": "/api/tools/updates/summary","group": "Shared","process": "Umbra main","display": "/api/tools/updates/summary","suffix": false},
  {"method": "GET","route": "/api/trash/list","group": "Gallery","process": "Umbra main","display": "/api/trash/list","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas-studio/projects","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas-studio/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects/:projectId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas-studio/projects/:projectId/revisions","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects/:projectId/revisions","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/background-removal/status","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/background-removal/status","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/projects","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/projects/:projectId/assets/:asset","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/assets/:asset","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/projects/:projectId/restore-points","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/restore-points","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/canvas/projects/:projectId/thumbnail","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/thumbnail","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/catalog","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/catalog","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/catalog/info","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/catalog/info","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/censor-review/projects","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/censor-review/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/assets/:filename","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/assets/:filename","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/export-links","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/export-links","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/h3-continuity/session/:sessionId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/h3-continuity/session/:sessionId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/h3-director/node-update","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/h3-director/node-update","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/image/completion-receipt","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/image/completion-receipt","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/jobs","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/jobs","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/jobs/:jobId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/jobs/:jobId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/models","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/models","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/projects","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/projects/:projectId/assets/:asset","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId/assets/:asset","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/inpaint/projects/:projectId/snapshots","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId/snapshots","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/media-tools/file/:token","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/file/:token","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/pipelines","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/pipelines","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/pipelines/resolve","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/pipelines/resolve","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/upscale/jobs","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/jobs","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/upscale/jobs/:jobId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/jobs/:jobId","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/video-controls","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-controls","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/video-jobs","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-jobs","suffix": false},
  {"method": "GET","route": "/api/umbra-ui/video-setup-readiness","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-setup-readiness","suffix": false},
  {"method": "GET","route": "/api/umbrabridge/comfyui/queue","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/comfyui/queue","suffix": false},
  {"method": "GET","route": "/api/umbrabridge/status","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/status","suffix": false},
  {"method": "GET","route": "/api/umbrabridge/vram/status","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/vram/status","suffix": false},
  {"method": "GET","route": "/api/user-config","group": "Shared","process": "Umbra main","display": "/api/user-config","suffix": false},
  {"method": "GET","route": "/api/video/official-workflows","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows","suffix": false},
  {"method": "GET","route": "/api/video/official-workflows/:workflowId/captures/:captureId","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows/:workflowId/captures/:captureId","suffix": false},
  {"method": "GET","route": "/api/video/official-workflows/:workflowId/source","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows/:workflowId/source","suffix": false},
  {"method": "GET","route": "/api/video/official-workflows/bridge.js","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows/bridge.js","suffix": false},
  {"method": "HEAD","route": "/api/comfy/staged-video-preview","group": "Shared","process": "Umbra main","display": "/api/comfy/staged-video-preview","suffix": false},
  {"method": "PATCH","route": "/api/powerprompter/queue-history","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-history","suffix": false},
  {"method": "PATCH","route": "/api/powerprompter/session","group": "Shared","process": "Umbra main","display": "/api/powerprompter/session","suffix": false},
  {"method": "PATCH","route": "/api/powerprompter/settings","group": "Shared","process": "Umbra main","display": "/api/powerprompter/settings","suffix": false},
  {"method": "PATCH","route": "/api/umbra-ui/censor-review/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId","suffix": false},
  {"method": "POST","route": "/api/app/update/run","group": "Shared","process": "Umbra main","display": "/api/app/update/run","suffix": false},
  {"method": "POST","route": "/api/app/update/start","group": "Shared","process": "Umbra main","display": "/api/app/update/start","suffix": false},
  {"method": "POST","route": "/api/app/updater/launch","group": "Shared","process": "Umbra main","display": "/api/app/updater/launch","suffix": false},
  {"method": "POST","route": "/api/app/updater/shutdown","group": "Shared","process": "Umbra main","display": "/api/app/updater/shutdown","suffix": false},
  {"method": "POST","route": "/api/booru/corpus/pause","group": "Data Forge","process": "Umbra main","display": "/api/booru/corpus/pause","suffix": false},
  {"method": "POST","route": "/api/booru/corpus/reset","group": "Data Forge","process": "Umbra main","display": "/api/booru/corpus/reset","suffix": false},
  {"method": "POST","route": "/api/booru/corpus/start","group": "Data Forge","process": "Umbra main","display": "/api/booru/corpus/start","suffix": false},
  {"method": "POST","route": "/api/booru/dataset-generator/control","group": "Data Forge","process": "Umbra main","display": "/api/booru/dataset-generator/control","suffix": false},
  {"method": "POST","route": "/api/booru/dataset-generator/run","group": "Data Forge","process": "Umbra main","display": "/api/booru/dataset-generator/run","suffix": false},
  {"method": "POST","route": "/api/booru/download","group": "Data Forge","process": "Umbra main","display": "/api/booru/download","suffix": false},
  {"method": "POST","route": "/api/comfy/copy-image","group": "Shared","process": "Umbra main","display": "/api/comfy/copy-image","suffix": false},
  {"method": "POST","route": "/api/comfy/copy-media","group": "Shared","process": "Umbra main","display": "/api/comfy/copy-media","suffix": false},
  {"method": "POST","route": "/api/comfy/ensure-media","group": "Shared","process": "Umbra main","display": "/api/comfy/ensure-media","suffix": false},
  {"method": "POST","route": "/api/comfy/upload-media","group": "Shared","process": "Umbra main","display": "/api/comfy/upload-media","suffix": false},
  {"method": "POST","route": "/api/data-forge/model-merge/blueprint","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/blueprint","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/blueprints/import","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/blueprints/import","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/cancel","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/cancel","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/inspect","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/inspect","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/lora-info","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/lora-info","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/recipes/delete","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/recipes/delete","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/recipes/save","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/recipes/save","suffix": true},
  {"method": "POST","route": "/api/data-forge/model-merge/start","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/model-merge/start","suffix": true},
  {"method": "POST","route": "/api/data-forge/wildcard-generator/generate","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/wildcard-generator/generate","suffix": false},
  {"method": "POST","route": "/api/data-forge/wildcard-generator/inspect","group": "Data Forge","process": "Umbra main","display": "/api/data-forge/wildcard-generator/inspect","suffix": false},
  {"method": "POST","route": "/api/dataset/api-keys","group": "Data Forge","process": "Umbra main","display": "/api/dataset/api-keys","suffix": false},
  {"method": "POST","route": "/api/dataset/auto-caption","group": "Data Forge","process": "Umbra main","display": "/api/dataset/auto-caption","suffix": false},
  {"method": "POST","route": "/api/dataset/create","group": "Data Forge","process": "Umbra main","display": "/api/dataset/create","suffix": false},
  {"method": "POST","route": "/api/dataset/delete","group": "Data Forge","process": "Umbra main","display": "/api/dataset/delete","suffix": false},
  {"method": "POST","route": "/api/dataset/download-selected","group": "Data Forge","process": "Umbra main","display": "/api/dataset/download-selected","suffix": false},
  {"method": "POST","route": "/api/dataset/preview","group": "Data Forge","process": "Umbra main","display": "/api/dataset/preview","suffix": false},
  {"method": "POST","route": "/api/dataset/save-caption","group": "Data Forge","process": "Umbra main","display": "/api/dataset/save-caption","suffix": false},
  {"method": "POST","route": "/api/datasets","group": "Data Forge","process": "Umbra main","display": "/api/datasets","suffix": false},
  {"method": "POST","route": "/api/datasets/:id/archive","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/archive","suffix": false},
  {"method": "POST","route": "/api/datasets/:id/concept","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/concept","suffix": false},
  {"method": "POST","route": "/api/datasets/:id/rename","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/rename","suffix": false},
  {"method": "POST","route": "/api/datasets/auto-tag-captions","group": "Data Forge","process": "Umbra main","display": "/api/datasets/auto-tag-captions","suffix": false},
  {"method": "POST","route": "/api/datasets/concept","group": "Data Forge","process": "Umbra main","display": "/api/datasets/concept","suffix": false},
  {"method": "POST","route": "/api/datasets/delete-images","group": "Data Forge","process": "Umbra main","display": "/api/datasets/delete-images","suffix": false},
  {"method": "POST","route": "/api/datasets/import-image","group": "Data Forge","process": "Umbra main","display": "/api/datasets/import-image","suffix": false},
  {"method": "POST","route": "/api/datasets/import-image-url","group": "Data Forge","process": "Umbra main","display": "/api/datasets/import-image-url","suffix": false},
  {"method": "POST","route": "/api/datasets/import-images","group": "Data Forge","process": "Umbra main","display": "/api/datasets/import-images","suffix": false},
  {"method": "POST","route": "/api/datasets/import-uploaded-image","group": "Data Forge","process": "Umbra main","display": "/api/datasets/import-uploaded-image","suffix": false},
  {"method": "POST","route": "/api/datasets/move-images","group": "Data Forge","process": "Umbra main","display": "/api/datasets/move-images","suffix": false},
  {"method": "POST","route": "/api/datasets/redownload-image","group": "Data Forge","process": "Umbra main","display": "/api/datasets/redownload-image","suffix": false},
  {"method": "POST","route": "/api/editor/config","group": "Shared","process": "Umbra main","display": "/api/editor/config","suffix": false},
  {"method": "POST","route": "/api/editor/image-tags","group": "Shared","process": "Umbra main","display": "/api/editor/image-tags","suffix": false},
  {"method": "POST","route": "/api/editor/meta","group": "Shared","process": "Umbra main","display": "/api/editor/meta","suffix": false},
  {"method": "POST","route": "/api/editor/meta/batch","group": "Shared","process": "Umbra main","display": "/api/editor/meta/batch","suffix": false},
  {"method": "POST","route": "/api/editor/order/clear","group": "Shared","process": "Umbra main","display": "/api/editor/order/clear","suffix": false},
  {"method": "POST","route": "/api/editor/order/set","group": "Shared","process": "Umbra main","display": "/api/editor/order/set","suffix": false},
  {"method": "POST","route": "/api/editor/presets","group": "Shared","process": "Umbra main","display": "/api/editor/presets","suffix": false},
  {"method": "POST","route": "/api/editor/save","group": "Shared","process": "Umbra main","display": "/api/editor/save","suffix": false},
  {"method": "POST","route": "/api/editor/sidecar/delete","group": "Shared","process": "Umbra main","display": "/api/editor/sidecar/delete","suffix": false},
  {"method": "POST","route": "/api/editor/sidecar/read","group": "Shared","process": "Umbra main","display": "/api/editor/sidecar/read","suffix": false},
  {"method": "POST","route": "/api/editor/sidecar/write","group": "Shared","process": "Umbra main","display": "/api/editor/sidecar/write","suffix": false},
  {"method": "POST","route": "/api/editor/tags","group": "Shared","process": "Umbra main","display": "/api/editor/tags","suffix": false},
  {"method": "POST","route": "/api/export/batch-zip","group": "Shared","process": "Umbra main","display": "/api/export/batch-zip","suffix": false},
  {"method": "POST","route": "/api/export/browse-folder","group": "Shared","process": "Umbra main","display": "/api/export/browse-folder","suffix": false},
  {"method": "POST","route": "/api/export/embed-metadata","group": "Shared","process": "Umbra main","display": "/api/export/embed-metadata","suffix": false},
  {"method": "POST","route": "/api/export/save","group": "Shared","process": "Umbra main","display": "/api/export/save","suffix": false},
  {"method": "POST","route": "/api/fs/archives","group": "Gallery","process": "Umbra main","display": "/api/fs/archives","suffix": false},
  {"method": "POST","route": "/api/fs/copy","group": "Gallery","process": "Umbra main","display": "/api/fs/copy","suffix": false},
  {"method": "POST","route": "/api/fs/download-jpeg-zip","group": "Gallery","process": "Umbra main","display": "/api/fs/download-jpeg-zip","suffix": false},
  {"method": "POST","route": "/api/fs/download-zip","group": "Gallery","process": "Umbra main","display": "/api/fs/download-zip","suffix": false},
  {"method": "POST","route": "/api/fs/mkdir","group": "Gallery","process": "Umbra main","display": "/api/fs/mkdir","suffix": false},
  {"method": "POST","route": "/api/fs/move","group": "Gallery","process": "Umbra main","display": "/api/fs/move","suffix": false},
  {"method": "POST","route": "/api/fs/move/undo","group": "Gallery","process": "Umbra main","display": "/api/fs/move/undo","suffix": false},
  {"method": "POST","route": "/api/fs/rename","group": "Gallery","process": "Umbra main","display": "/api/fs/rename","suffix": false},
  {"method": "POST","route": "/api/fs/rename/batch","group": "Gallery","process": "Umbra main","display": "/api/fs/rename/batch","suffix": false},
  {"method": "POST","route": "/api/fs/reorder","group": "Gallery","process": "Umbra main","display": "/api/fs/reorder","suffix": false},
  {"method": "POST","route": "/api/fs/reveal","group": "Gallery","process": "Umbra main","display": "/api/fs/reveal","suffix": false},
  {"method": "POST","route": "/api/fs/tags/add","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/add","suffix": false},
  {"method": "POST","route": "/api/fs/tags/remove","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/remove","suffix": false},
  {"method": "POST","route": "/api/fs/tags/set","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/set","suffix": false},
  {"method": "POST","route": "/api/fs/transfer/cancel","group": "Gallery","process": "Umbra main","display": "/api/fs/transfer/cancel","suffix": false},
  {"method": "POST","route": "/api/fs/transfer/reconcile","group": "Gallery","process": "Umbra main","display": "/api/fs/transfer/reconcile","suffix": false},
  {"method": "POST","route": "/api/fs/trash/move","group": "Gallery","process": "Umbra main","display": "/api/trash/delete","suffix": false},
  {"method": "POST","route": "/api/fs/upload","group": "Gallery","process": "Umbra main","display": "/api/fs/upload","suffix": false},
  {"method": "POST","route": "/api/fs/write","group": "Gallery","process": "Umbra main","display": "/api/fs/write","suffix": false},
  {"method": "POST","route": "/api/gallery-bridge/fs/empty-folders/delete","group": "Gallery","process": "Umbra main","display": "/api/fs/empty-folders/delete","suffix": false},
  {"method": "POST","route": "/api/gallery-bridge/fs/empty-folders/preview","group": "Gallery","process": "Umbra main","display": "/api/fs/empty-folders/preview","suffix": false},
  {"method": "POST","route": "/api/gallery-bridge/fs/tags/add","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/add","suffix": false},
  {"method": "POST","route": "/api/gallery-bridge/fs/tags/remove","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/remove","suffix": false},
  {"method": "POST","route": "/api/gallery-bridge/fs/tags/set","group": "Gallery","process": "Umbra main","display": "/api/fs/tags/set","suffix": false},
  {"method": "POST","route": "/api/local-server-apps/open-folder","group": "Shared","process": "Umbra main","display": "/api/local-server-apps/open-folder","suffix": false},
  {"method": "POST","route": "/api/metadata/caption-image","group": "Shared","process": "Umbra main","display": "/api/metadata/caption-image","suffix": false},
  {"method": "POST","route": "/api/metadata/scan","group": "Shared","process": "Umbra main","display": "/api/metadata/scan","suffix": false},
  {"method": "POST","route": "/api/metadata/scan-upload","group": "Shared","process": "Umbra main","display": "/api/metadata/scan-upload","suffix": false},
  {"method": "POST","route": "/api/metadata/tag-waifu","group": "Shared","process": "Umbra main","display": "/api/metadata/tag-waifu","suffix": false},
  {"method": "POST","route": "/api/model-manager/civitai/auth","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/auth","suffix": false},
  {"method": "POST","route": "/api/model-manager/civitai/download","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/civitai/download","suffix": false},
  {"method": "POST","route": "/api/model-manager/downloads/:id/cancel","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/downloads/:id/cancel","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/copy","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/copy","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/delete","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/delete","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/mkdir","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/mkdir","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/move","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/move","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/rename","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/rename","suffix": false},
  {"method": "POST","route": "/api/model-manager/fs/reveal","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/fs/reveal","suffix": false},
  {"method": "POST","route": "/api/model-manager/inspect","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/inspect","suffix": false},
  {"method": "POST","route": "/api/model-manager/opened-models","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/opened-models","suffix": false},
  {"method": "POST","route": "/api/model-manager/opened-models/delete","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/opened-models/delete","suffix": false},
  {"method": "POST","route": "/api/model-manager/opened-models/refresh","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/opened-models/refresh","suffix": false},
  {"method": "POST","route": "/api/model-manager/reconcile","group": "Model Manager","process": "Umbra main","display": "/api/model-manager/reconcile","suffix": false},
  {"method": "POST","route": "/api/onboarding/browse-source","group": "Shared","process": "Umbra main","display": "/api/onboarding/browse-source","suffix": false},
  {"method": "POST","route": "/api/onboarding/complete","group": "Shared","process": "Umbra main","display": "/api/onboarding/complete","suffix": false},
  {"method": "POST","route": "/api/onboarding/inspect-source","group": "Shared","process": "Umbra main","display": "/api/onboarding/inspect-source","suffix": false},
  {"method": "POST","route": "/api/onboarding/migrate","group": "Shared","process": "Umbra main","display": "/api/onboarding/migrate","suffix": false},
  {"method": "POST","route": "/api/powerprompter/api-workflows/import","group": "Shared","process": "Umbra main","display": "/api/powerprompter/api-workflows/import","suffix": false},
  {"method": "POST","route": "/api/powerprompter/cards","group": "Shared","process": "Umbra main","display": "/api/powerprompter/cards","suffix": false},
  {"method": "POST","route": "/api/powerprompter/diagnostics-log","group": "Shared","process": "Umbra main","display": "/api/powerprompter/diagnostics-log","suffix": false},
  {"method": "POST","route": "/api/powerprompter/favorites","group": "Shared","process": "Umbra main","display": "/api/powerprompter/favorites","suffix": false},
  {"method": "POST","route": "/api/powerprompter/index","group": "Shared","process": "Umbra main","display": "/api/powerprompter/index","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queue-history","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-history","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queue-prompts/build","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-prompts/build","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queue-state","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue-state","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queue/emergency-cancel","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue/emergency-cancel","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queue/mutate","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queue/mutate","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queues","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queues","suffix": false},
  {"method": "POST","route": "/api/powerprompter/queues/restore","group": "Shared","process": "Umbra main","display": "/api/powerprompter/queues/restore","suffix": false},
  {"method": "POST","route": "/api/powerprompter/selections","group": "Shared","process": "Umbra main","display": "/api/powerprompter/selections","suffix": false},
  {"method": "POST","route": "/api/powerprompter/session/open","group": "Shared","process": "Umbra main","display": "/api/powerprompter/session/open","suffix": false},
  {"method": "POST","route": "/api/powerprompter/settings","group": "Shared","process": "Umbra main","display": "/api/powerprompter/settings","suffix": false},
  {"method": "POST","route": "/api/remote/auth/login","group": "Shared","process": "Umbra main","display": "/api/remote/auth/login","suffix": false},
  {"method": "POST","route": "/api/remote/auth/logout","group": "Shared","process": "Umbra main","display": "/api/remote/auth/logout","suffix": false},
  {"method": "POST","route": "/api/remote/auth/pair","group": "Shared","process": "Umbra main","display": "/api/remote/auth/pair","suffix": false},
  {"method": "POST","route": "/api/remote/auth/pair-token","group": "Shared","process": "Umbra main","display": "/api/remote/auth/pair-token","suffix": false},
  {"method": "POST","route": "/api/remote/auth/setup","group": "Shared","process": "Umbra main","display": "/api/remote/auth/setup","suffix": false},
  {"method": "POST","route": "/api/remote/devices/rename","group": "Shared","process": "Umbra main","display": "/api/remote/devices/rename","suffix": false},
  {"method": "POST","route": "/api/remote/devices/revoke","group": "Shared","process": "Umbra main","display": "/api/remote/devices/revoke","suffix": false},
  {"method": "POST","route": "/api/remote/metrics","group": "Shared","process": "Umbra main","display": "/api/remote/metrics","suffix": false},
  {"method": "POST","route": "/api/remote/settings","group": "Shared","process": "Umbra main","display": "/api/remote/settings","suffix": false},
  {"method": "POST","route": "/api/remote/tailscale/serve","group": "Shared","process": "Umbra main","display": "/api/remote/tailscale/serve","suffix": false},
  {"method": "POST","route": "/api/remote/test-url","group": "Shared","process": "Umbra main","display": "/api/remote/test-url","suffix": false},
  {"method": "POST","route": "/api/server/shutdown","group": "Shared","process": "Umbra main","display": "/api/server/shutdown","suffix": false},
  {"method": "POST","route": "/api/settings","group": "Shared","process": "Umbra main","display": "/api/settings","suffix": false},
  {"method": "POST","route": "/api/settings/bundle","group": "Shared","process": "Umbra main","display": "/api/settings/bundle","suffix": false},
  {"method": "POST","route": "/api/tools/actions","group": "Shared","process": "Umbra main","display": "/api/tools/actions","suffix": false},
  {"method": "POST","route": "/api/tools/comfyui/version","group": "Shared","process": "Umbra main","display": "/api/tools/comfyui/version","suffix": false},
  {"method": "POST","route": "/api/trash/delete","group": "Gallery","process": "Umbra main","display": "/api/trash/delete","suffix": false},
  {"method": "POST","route": "/api/trash/delete-direct","group": "Gallery","process": "Umbra main","display": "/api/trash/delete-direct","suffix": false},
  {"method": "POST","route": "/api/trash/empty","group": "Gallery","process": "Umbra main","display": "/api/trash/empty","suffix": false},
  {"method": "POST","route": "/api/trash/permanent-delete","group": "Gallery","process": "Umbra main","display": "/api/trash/permanent-delete","suffix": false},
  {"method": "POST","route": "/api/trash/restore","group": "Gallery","process": "Umbra main","display": "/api/trash/restore","suffix": false},
  {"method": "POST","route": "/api/trash/retention","group": "Gallery","process": "Umbra main","display": "/api/trash/retention","suffix": false},
  {"method": "POST","route": "/api/trash/system","group": "Gallery","process": "Umbra main","display": "/api/trash/system","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas-studio/projects/:projectId/revisions/:revisionId/restore","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects/:projectId/revisions/:revisionId/restore","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/background-removal/cancel","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/background-removal/cancel","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/projects/:projectId/fork","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/fork","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/projects/:projectId/restore-points","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/restore-points","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/projects/:projectId/restore-points/:revisionId/restore","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId/restore-points/:revisionId/restore","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/remove-background","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/remove-background","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/canvas/save","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/save","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/approve-uncensored","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/approve-uncensored","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/detect","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/detect","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/export","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/export","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/render","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/render","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/review","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId/review","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/h3-prompt-forge/model-folder/open","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/h3-prompt-forge/model-folder/open","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/image/replace-source","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/image/replace-source","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/control-preprocess","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/control-preprocess","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/jobs/:jobId/cancel","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/jobs/:jobId/cancel","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/jobs/:jobId/skip","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/jobs/:jobId/skip","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/layer-upscale","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/layer-upscale","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/projects/:projectId/snapshots","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId/snapshots","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/projects/:projectId/snapshots/:revisionId/restore","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId/snapshots/:revisionId/restore","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/inpaint/remove-background","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/remove-background","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/browse-output-folder","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/browse-output-folder","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/browse-source-files","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/browse-source-files","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/cancel","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/cancel","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/censor","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/censor","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/video-to-gif","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/video-to-gif","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/watermark","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/watermark","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/media-tools/watermark-assets","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/media-tools/watermark-assets","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/queue/control","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/queue/control","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/upscale","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/upscale/browse-output-folder","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/browse-output-folder","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/upscale/jobs/:jobId/cancel","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/jobs/:jobId/cancel","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/upscale/stage","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/stage","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/upscale/stage/cleanup","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/upscale/stage/cleanup","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/video-controls","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-controls","suffix": false},
  {"method": "POST","route": "/api/umbra-ui/video-jobs/clear","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-jobs/clear","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/backend/start","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/backend/start","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/backend/stop","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/backend/stop","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/backend/stop-all","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/backend/stop-all","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/backend/wait-ready","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/backend/wait-ready","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/comfyui/interrupt","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/comfyui/interrupt","suffix": false},
  {"method": "POST","route": "/api/umbrabridge/comfyui/queue/clear","group": "Shared","process": "Umbra main","display": "/api/umbrabridge/comfyui/queue/clear","suffix": false},
  {"method": "POST","route": "/api/user-config","group": "Shared","process": "Umbra main","display": "/api/user-config","suffix": false},
  {"method": "POST","route": "/api/video/official-workflows/:workflowId/capture","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows/:workflowId/capture","suffix": false},
  {"method": "POST","route": "/api/video/official-workflows/:workflowId/import","group": "Shared","process": "Umbra main","display": "/api/video/official-workflows/:workflowId/import","suffix": false},
  {"method": "PUT","route": "/api/datasets/:id/concept/:id/settings","group": "Data Forge","process": "Umbra main","display": "/api/datasets/:id/concept/:id/settings","suffix": false},
  {"method": "PUT","route": "/api/editor/presets/:id","group": "Shared","process": "Umbra main","display": "/api/editor/presets/:id","suffix": false},
  {"method": "PUT","route": "/api/powerprompter/wildcards","group": "Shared","process": "Umbra main","display": "/api/powerprompter/wildcards","suffix": false},
  {"method": "PUT","route": "/api/umbra-ui/canvas-studio/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas-studio/projects/:projectId","suffix": false},
  {"method": "PUT","route": "/api/umbra-ui/canvas/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/canvas/projects/:projectId","suffix": false},
  {"method": "PUT","route": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/censor-review/projects/:projectId/items/:itemId","suffix": false},
  {"method": "PUT","route": "/api/umbra-ui/inpaint/projects/:projectId","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/inpaint/projects/:projectId","suffix": false},
  {"method": "PUT","route": "/api/umbra-ui/video-controls","group": "Umbra UI","process": "Umbra main","display": "/api/umbra-ui/video-controls","suffix": false},
  {"method": "GET","route": "/api/models/local","group": "Model Manager","process": "Umbra main","display": "/api/models/local","suffix": false},
  {"method": "GET","route": "/api/civitai/models","group": "Model Manager","process": "Umbra main","display": "/api/civitai/models","suffix": false},
  {"method": "POST","route": "/api/models/download","group": "Model Manager","process": "Umbra main","display": "/api/models/download","suffix": false}
] as const;
export const actionMethods = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'CONNECT', 'TRACE'] as const;
export function safeMethod(method: string): string {
  return (actionMethods as readonly string[]).includes(method) ? method : 'OTHER';
}
const compiled = actionRoutes.map(row => {
  const escaped = row.route.split('/').map(segment => segment.startsWith(':') ? '[^/]+' : segment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('/');
  let pattern = escaped;
  if (row.suffix) pattern = '/api/data-forge/model-merge(?:/.*)?/' + row.route.slice('/api/data-forge/model-merge/'.length);
  // These server guards consume the entire remainder, including embedded slashes.
  if (row.route === '/api/files/datasets/:relativePath' || row.route === '/api/umbra-ui/agent/:rest') pattern = escaped.replace(/\[\^\/\]\+$/, '.*');
  if (/^\/api\/umbra-ui\/(canvas|inpaint)\/projects\/:projectId$/.test(row.route)) pattern = escaped.replace(/\[\^\/\]\+$/, '.*');
  if (/^\/api\/umbra-ui\/(canvas|inpaint)\/projects\/:projectId\/assets\/:asset$/.test(row.route)) pattern = row.route.replace(':projectId', '.+').replace(':asset', '.+');
  if (/^\/api\/umbra-ui\/(inpaint|upscale)\/jobs\/:jobId(?:\/(cancel|skip))?$/.test(row.route)
    || row.route === '/api/umbra-ui/h3-continuity/session/:sessionId'
    || row.route === '/api/umbra-ui/media-tools/file/:token'
    || /^\/api\/editor\/(config|presets|tags)\/:/.test(row.route)
    || row.route === '/api/powerprompter/wildcards/:name') pattern = row.route.replace(/:[A-Za-z]+/, '.*');
  if (/^\/api\/umbra-ui\/(inpaint|upscale)\/jobs\/:jobId\/(cancel|skip)$/.test(row.route)) {
    const [prefix, suffix] = row.route.split(':jobId/');
    pattern = prefix.slice(0, -1) + '(?:/.*)?/' + suffix;
  }
  return { row, re: new RegExp('^' + pattern + '$') };
}).sort((a,b) => b.row.route.split('/').length - a.row.route.split('/').length || Number(a.row.route.includes(':')) - Number(b.row.route.includes(':')));
const namespaces: readonly [string, ActionGroup][] = [
 ['/api/gallery-bridge/', 'Gallery'], ['/api/fs/', 'Gallery'],
 ['/api/umbra-ui/', 'Umbra UI'], ['/api/data-forge/', 'Data Forge'],
 ['/api/dataset/', 'Data Forge'], ['/api/datasets/', 'Data Forge'],
 ['/api/model-manager/', 'Model Manager'], ['/api/models/', 'Model Manager'], ['/api/civitai/', 'Model Manager'],
];
export function classifyAction(path: string, method: string, process: ActionProcess): ActionIdentity | null {
  if (path.startsWith('/bridge/api/')) path = path.slice('/bridge'.length);
  if (!path.startsWith('/api/')) return null;
  if (method === 'OPTIONS') return { route: '/api/:preflight', group: 'Shared' };
  const matches = compiled.filter(entry => entry.row.process === process && entry.re.test(path));
  const match = matches.find(entry => entry.row.method === method || entry.row.method === 'ANY') || matches[0];
  if (match) return { route: match.row.display, group: match.row.group };
  const namespace = namespaces.find(([prefix]) => path.startsWith(prefix));
  return namespace ? { route: namespace[0] + ':unmatched', group: namespace[1] } : { route: '/api/:unmatched', group: 'Shared' };
}
