import type { ImageMetadata } from '@/utils/metadata';

export const POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_KEY = 'power-prompter:pending-image-restore';
export const POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_EVENT = 'umbra:power-prompter-image-restore';

export interface PowerPrompterImageRestoreHandoff {
  version: 1;
  path: string;
  name: string;
  source: string;
  createdAt: number;
}

function normalizeRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function normalizePath(value: unknown): string {
  return String(value || '').trim().replace(/\\/g, '/');
}

export function normalizePowerPrompterImageRestoreHandoff(
  value: unknown,
): PowerPrompterImageRestoreHandoff | null {
  const source = normalizeRecord(value);
  const path = normalizePath(source.path);
  if (!path || !/\.png$/i.test(path)) return null;
  return {
    version: 1,
    path,
    name: String(source.name || path.split('/').pop() || 'Power Prompter image').trim(),
    source: String(source.source || 'gallery').trim() || 'gallery',
    createdAt: Number.isFinite(Number(source.createdAt)) ? Number(source.createdAt) : Date.now(),
  };
}

export function stagePowerPrompterImageRestoreHandoff(
  detail: Omit<PowerPrompterImageRestoreHandoff, 'version' | 'createdAt'>,
): PowerPrompterImageRestoreHandoff {
  const payload = normalizePowerPrompterImageRestoreHandoff({
    ...detail,
    version: 1,
    createdAt: Date.now(),
  });
  if (!payload) throw new Error('Choose a PNG generated by Power Prompter.');
  if (typeof window !== 'undefined') {
    try {
      window.sessionStorage.setItem(
        POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_KEY,
        JSON.stringify(payload),
      );
    } catch {
      // The live event still works when session storage is unavailable.
    }
    window.dispatchEvent(new CustomEvent(POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_EVENT, {
      detail: payload,
    }));
  }
  return payload;
}

export function takePendingPowerPrompterImageRestoreHandoff(): PowerPrompterImageRestoreHandoff | null {
  if (typeof window === 'undefined') return null;
  let stored = '';
  try {
    stored = window.sessionStorage.getItem(POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_KEY) || '';
    window.sessionStorage.removeItem(POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_KEY);
  } catch {
    return null;
  }
  if (!stored) return null;
  try {
    return normalizePowerPrompterImageRestoreHandoff(JSON.parse(stored));
  } catch {
    return null;
  }
}

export function clearPendingPowerPrompterImageRestoreHandoff(): void {
  if (typeof window === 'undefined') return;
  try {
    window.sessionStorage.removeItem(POWER_PROMPTER_IMAGE_RESTORE_HANDOFF_KEY);
  } catch {
    // Best effort.
  }
}

export async function fetchPowerPrompterImageRestoreMetadata(
  pathValue: string,
): Promise<ImageMetadata> {
  const path = normalizePath(pathValue);
  if (!path || !/\.png$/i.test(path)) {
    throw new Error('Choose a PNG generated by Power Prompter.');
  }
  const response = await fetch(
    `/api/fs/metadata?${new URLSearchParams({ path }).toString()}`,
    { cache: 'no-store' },
  );
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(String(payload?.error || 'Failed to read image metadata.'));
  }
  return payload as ImageMetadata;
}
